# Port d'entree unique pour le client (Postman/Front-end)
server.port=8080
spring.application.name=gateway-service
# Connexion ANBSP l'annuaire Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# --- CONFIGURATION DES ROUTES ---
# Route 1 : Redirection vers le Product Service
spring.cloud.gateway.routes[0].id=product-service-route
spring.cloud.gateway.routes[0].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/products/**
# Route 2 : Redirection vers le Order Service
spring.cloud.gateway.routes[1].id=order-service-route
spring.cloud.gateway.routes[1].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/orders/**